// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Shadow database HARUS beda dari database utama. Set SHADOW_DATABASE_URL di .env (lihat ENV_SETUP.md).
    ...(process.env["SHADOW_DATABASE_URL"] && {
      shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
    }),
  },
});
